In [81]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.activations import linear, relu, sigmoid
import numpy as np
import pandas
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.optimizers.legacy import Adam
from tensorflow.keras.regularizers import L2

print(pandas.__version__)

# Get and scale training data
scaler = StandardScaler()

data_train = pandas.read_csv("./student/student-mat-clean-train.csv").to_numpy()
print(data_train)

X_train = scaler.fit_transform(data_train[:,1:-1])
y_train = data_train[:,0]
print("Data:")
print(data)
print("X")
print(data_train[:,1:-1])
print("Now standardized")
print(X_train)
# print("y")
# print(y_train)

# Load and scale testing data

data_test = pandas.read_csv("./student/student-mat-clean-test.csv").to_numpy()

X_test = scaler.transform(data_test[:,1:-1])
y_test = data_test[:,0]

print("Num gpus available: ")
print(len(tf.config.experimental.list_physical_devices('GPU')))

# print(tf.reduce_sum(tf.random.normal([1000, 1000])))

# Number of units picked with no particular logic behind it


1.5.2
[[ 0  2  3  4  6]
 [ 0  2  3  2 10]
 [ 0  2  4  2 15]
 ...
 [ 1  2  1  3 15]
 [ 1  1  4  3  7]
 [ 1  1  4  3  6]]
Data:
[[ 0  2  3  4  6  6]
 [ 0  2  3  3  4  6]
 [ 0  2  3  2 10 10]
 ...
 [ 0  1  5  3  3  7]
 [ 0  1  4  1  0 10]
 [ 0  1  2  3  5  9]]
X
[[2 3 4]
 [2 3 2]
 [2 4 2]
 [2 4 4]
 [2 1 4]
 [2 2 2]
 [2 5 1]
 [2 3 3]
 [1 3 3]
 [2 4 3]
 [1 4 4]
 [3 2 3]
 [2 3 2]
 [1 5 5]
 [1 1 3]
 [2 4 1]
 [1 4 2]
 [2 5 1]
 [2 4 4]
 [3 3 2]
 [1 2 2]
 [1 2 4]
 [2 3 3]
 [2 4 2]
 [2 3 1]
 [1 4 3]
 [1 5 1]
 [3 4 3]
 [1 3 1]
 [2 3 3]
 [1 4 1]
 [2 3 5]
 [2 3 3]
 [2 3 3]
 [2 3 3]
 [1 5 5]
 [1 3 4]
 [1 3 4]
 [2 2 2]
 [2 3 2]
 [2 2 3]
 [2 4 4]
 [2 4 3]
 [3 4 4]
 [2 4 3]
 [4 3 3]
 [4 4 2]
 [4 3 2]
 [4 3 3]
 [1 3 2]
 [2 3 3]
 [4 4 3]
 [1 5 1]
 [2 4 3]
 [3 3 2]
 [2 4 4]
 [2 3 4]
 [3 3 3]
 [2 4 2]
 [2 1 3]
 [2 3 3]
 [2 3 3]
 [4 1 2]
 [1 3 3]
 [1 3 4]
 [3 3 5]
 [2 3 5]
 [2 4 4]
 [4 3 3]
 [4 1 2]
 [3 3 3]
 [3 1 2]
 [2 1 2]
 [1 5 2]
 [2 4 4]
 [2 4 3]
 [1 4 2]
 [2 2 4]
 [2 2 3]
 [4 5 4]
 [1 4 4]
 [1 3 3]
 [

In [85]:
# Build and train model
model = Sequential([
    Dense(units = 80, activation = "relu", kernel_regularizer=L2(0.005)),
    Dense(units = 40, activation = "relu", kernel_regularizer=L2(0.005)),
    Dense(units = 20, activation = "relu", kernel_regularizer=L2(0.005)), 
    Dense(units = 1, activation = "sigmoid", kernel_regularizer=L2(0.005)), # Output
])

model.compile(loss = tf.keras.losses.BinaryCrossentropy(),
             optimizer=Adam())

model.fit(X_train,y_train, epochs=150)
print("reached end!")

Epoch 1/150


2022-12-29 23:33:21.288386: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


10/10 [==============================] - 1s 18ms/step - loss: 1.1191
Epoch 2/150
10/10 [==============================] - 0s 15ms/step - loss: 1.0555
Epoch 3/150
10/10 [==============================] - 0s 12ms/step - loss: 1.0060
Epoch 4/150
10/10 [==============================] - 0s 12ms/step - loss: 0.9662
Epoch 5/150
10/10 [==============================] - 0s 15ms/step - loss: 0.9389
Epoch 6/150
10/10 [==============================] - 0s 14ms/step - loss: 0.9115
Epoch 7/150
10/10 [==============================] - 0s 12ms/step - loss: 0.8875
Epoch 8/150
10/10 [==============================] - 0s 12ms/step - loss: 0.8660
Epoch 9/150
10/10 [==============================] - 0s 12ms/step - loss: 0.8461
Epoch 10/150
10/10 [==============================] - 0s 12ms/step - loss: 0.8287
Epoch 11/150
10/10 [==============================] - 0s 13ms/step - loss: 0.8121
Epoch 12/150
10/10 [==============================] - 0s 14ms/step - loss: 0.7978
Epoch 13/150
10/10 [=================

10/10 [==============================] - 0s 12ms/step - loss: 0.6403
Epoch 102/150
10/10 [==============================] - 0s 13ms/step - loss: 0.6396
Epoch 103/150
10/10 [==============================] - 0s 12ms/step - loss: 0.6402
Epoch 104/150
10/10 [==============================] - 0s 14ms/step - loss: 0.6405
Epoch 105/150
10/10 [==============================] - 0s 13ms/step - loss: 0.6402
Epoch 106/150
10/10 [==============================] - 0s 12ms/step - loss: 0.6402
Epoch 107/150
10/10 [==============================] - 0s 12ms/step - loss: 0.6408
Epoch 108/150
10/10 [==============================] - 0s 12ms/step - loss: 0.6402
Epoch 109/150
10/10 [==============================] - 0s 14ms/step - loss: 0.6395
Epoch 110/150
10/10 [==============================] - 0s 12ms/step - loss: 0.6397
Epoch 111/150
10/10 [==============================] - 0s 13ms/step - loss: 0.6390
Epoch 112/150
10/10 [==============================] - 0s 13ms/step - loss: 0.6398
Epoch 113/150
10/1

In [86]:
probabilities_train = model.predict(X_train)
predictions_train = np.where(probabilities_train >= 0.5, 1, 0)

misclassifications_train = 0

for i in range(len(predictions_train)):
    if (predictions_train[i] == y_train[i]):
        misclassifications_train += 1
        
print("train ratio of correct")
print(misclassifications_train/len(predictions_train))

##########

probabilities_test = model.predict(X_test)
predictions_test = np.where(probabilities_test >= 0.5, 1, 0)

misclassifications_test = 0

for i in range(len(predictions)):
    if (predictions_train[i] == y_test[i]):
        misclassifications_test += 1

print("test ratio of correct")
print(misclassifications_test/len(predictions_test))

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: closure mismatch, requested ('self', 'step_function'), but source function had ()
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: closure mismatch, requested ('self', 'step_function'), but source function had ()
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
10/10 [==============================] - 0s 4ms/step
train ratio of correct
0.6655405405405406
4/4 [==============================] - 0s 6ms/step
test ratio of correct
0.6666666666666666


2022-12-29 23:33:43.786955: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
